fix processor
Apollo-LW/resource pull request #3
Opened 2020-12-29 20:55 UTC by hindnasser

2020-12-29 23:05 UTC, MrMoon commented on src/main/java/com/apollo/resource/controller/ResourceController.java
> +    @PutMapping(value= "/{resourceId}")
no need for the {resourceId}

2020-12-29 23:07 UTC, MrMoon commented on src/main/java/com/apollo/resource/controller/ResourceController.java
> +    public Mono<Boolean> shareResource (@PathVariable ("flag") Boolean flag ,@RequestBody String userId, String resourceId){
resourceId should also be @RequestBody, so create an object the have userId and resourceId and just @RequstBody once

2020-12-29 23:08 UTC, MrMoon commented on src/main/java/com/apollo/resource/model/Document.java
> +    private String documentUrl, OwnerId = this.getResourcesOwnerId();
OwnerId should be ownerId, camelCase convention

2020-12-29 23:14 UTC, MrMoon approved these changes

2020-12-29 23:16 UTC, MrMoon approved these changes

2020-12-30 16:23 UTC, MrMoon commented on src/main/java/com/apollo/resource/model/ResourceType.java
> +    Document, Video
The naming convention for the enums are ALLCAPS
So,
DOCUMENT, VIDEO

2020-12-30 16:24 UTC, MrMoon approved these changes

2020-12-30 16:25 UTC, hindnasser commented on src/main/java/com/apollo/resource/model/ResourceType.java
> +    Document, Video
Done

2020-12-30 16:34 UTC, MrMoon approved these changes

2020-12-30 20:36 UTC, MrMoon approved these changes

2020-12-30 22:08 UTC, MrMoon requested changes

2020-12-30 22:08 UTC, MrMoon commented on src/main/resources/application.yml
>    port: 8081
port 8081 is already taken by the course microservice, make it 8084

2021-02-17 13:03 UTC, MrMoon approved these changes

2021-02-17 13:03 UTC, merged